django-study/simpleProject/book/urls.py
from django.urls import path
from .views import (index,
                    add,
                    edit)

app_name = "book"

urlpatterns = [
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<int:id>', edit, name='edit'),
]

django-study/simpleProject/simpleProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/',include("book.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-study/simpleProject/book/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    name    = models.CharField(max_length=50)
    author  = models.CharField(max_length=50)
    photo   = models.ImageField(upload_to='books')
    rate    = models.IntegerField()
    date    = models.DateField()

    def __str__(self):
        return self.name + " - " + self.author

django-study/simpleProject/book/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

django-study/simpleProject/book/views.py
from django.shortcuts import render, HttpResponse
from .models import Book
from .forms import BookForm
from django.contrib import messages
# Create your views here.

def index(request):
    books = Book.objects.all()
    context = {
        'books':books,
    }
    return render(request, "book/index.html", context)

def add(request):
    if request.method == "GET":
        return render(request, 'book/add.html')
        
    if request.method == "POST":
        form = BookForm(request.POST,request.FILES)
        if form.is_valid():
            name    = form.cleaned_data.get('name')
            author  = form.cleaned_data.get('author')
            date    = form.cleaned_data.get('date')
            rate    = form.cleaned_data.get('rate')
            photo   = form.cleaned_data.get('photo')
            Book.objects.create(name=name, author=author, date=date, rate=rate, photo=photo)
        else:
            messages.error(request, form.errors)

        return render(request, 'book/add.html')

def edit(request, id):
    if request.method == "GET":
        book = Book.objects.get(pk=id)
        context = {
            'book':book
        }
        return render(request, 'book/edit.html', context)
    elif request.method == "POST":
        book = Book.objects.get(pk=id)
        context = {
            'book':book
        }
        form = BookForm(request.POST,request.FILES)
        if form.is_valid():
            name    = form.cleaned_data.get('name')
            author  = form.cleaned_data.get('author')
            date    = form.cleaned_data.get('date')
            rate    = form.cleaned_data.get('rate')
            photo   = form.cleaned_data.get('photo')
            Book.objects.create(name=name, author=author, date=date, rate=rate, photo=photo)
        else:
            messages.error(request, form.errors)
    return render(request, 'book/edit.html', context)

        

django-study/simpleProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- bootstrap css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Django - Study</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content  %}

    {% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
</body>
</html>

django-study/simpleProject/templates/book/add.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-5 justify-content-center">

      <div class="col-md-5">
        <div class="col-md-11 card">
          <div class="card-body">
    <form action="{% url 'book:add' %}" method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
            <div class="form-group">
          <img height="128" class="img-responsive text-center mb-3"
               :src="product.selectedImage == null ? '/src/assets/default.png' : product.selectedImage">
          <input ref="file" type="file" style="display: none;" @change="onChange($event)" class="form-control">
          <button class="btn btn-outline-secondary " type="button" @click="$refs.file.click()">Resim Seç</button>
            </div>
            <div class="form-group">
              <label>Book Name</label>
              <input type="text" name="name"  class="form-control" placeholder="book name..">
            </div>
            <div class="form-group">
              <label>Author Name</label>
              <input type="text" name="author" class="form-control" placeholder="author name..">
            </div>
            <div class="row">
              <div class="form-group col-md-5">
                    <label for="date">Date</label>
                    <input class="form-control" type="date" value="2020-01-01" name="date" id="date" aria-describedby="dateHelp" style="max-width: 320px;">
                    <small id="dateHelp" class="form-text text-muted">Enter the date of reading</small>
              </div>
              <div class="col-md-7">
                  <label for="image" style="display: block;"class="ml-3">Rate</label>
                <div class="custom-control custom-radio ml-2" style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value1" value="1" >
                    <label class="custom-control-label mr-1" for="value1">1</label>
                </div>
                <div class="custom-control custom-radio " style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value2" value="2" >
                    <label class="custom-control-label mr-1" for="value2">2</label>
                </div>
                <div class="custom-control custom-radio " style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value3" value="3" >
                    <label class="custom-control-label mr-1" for="value3">3</label>
                </div>
                <div class="custom-control custom-radio " style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value4" value="4" >
                    <label class="custom-control-label mr-1" for="value4">4</label>
                </div>
                <div class="custom-control custom-radio " style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value5" value="5" >
                    <label class="custom-control-label mr-1" for="value5">5</label>
                </div>
              </div>

            </div>
            <button class="btn btn-outline-info btn-block">Add!</button>
          </div>
        </div>
      </div>
      </form>
    </div>

{%  endblock %}

django-study/simpleProject/templates/book/edit.html
{% extends 'base.html' %}

{% block content %}
<style>
form { all: none; }
</style>
<div class="row mt-5">

      <div class="card offset-2 col-md-3">
        <div class="card-body tex-center d-flex align-items-center flex-column">
          <!-- Gayet güzel, dosya seç görselini override etti. ref önemli -->
          <img height="128" class="img-responsive text-center mb-3" src="{{book.photo.url}}" >
          <input type="file" style="display: none;" name="photo"  class="form-control">
          <button class="btn btn-outline-secondary " type="button"">Choose Image</button>
        </div>
      </div>
      <div class="col-md-5">
        <div class="col-md-11 card">
          <div class="card-body">
    <form action="{% url 'book:edit' book.id %}" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
            <div class="form-group">
              <label>Book Name</label>
              <input type="text" name="name"  class="form-control" value="{{book.name}}">
            </div>
            <div class="form-group">
              <label>Author Name</label>
              <input type="text" name="author"  class="form-control" value="{{book.author}}">
            </div>
            <div class="row">
              <div class="form-group col-md-5">
                    <label for="date">Date</label>
                    <input class="form-control" type="date" value="2020-01-01" name="date" id="date" aria-describedby="dateHelp" style="max-width: 320px;">

              </div>
              <div class="col-md-7">
                  <label for="image" style="display: block;"class="ml-3">Rate</label>
                <div class="custom-control custom-radio ml-2" style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value1" value="1" {% if book.rate == 1 %} checked {% endif %} >
                    <label class="custom-control-label mr-1" for="value1">1</label>
                </div>
                <div class="custom-control custom-radio " style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value2" value="2" {% if book.rate == 2 %} checked {% endif %} >
                    <label class="custom-control-label mr-1" for="value2">2</label>
                </div>
                <div class="custom-control custom-radio " style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value3" value="3" {% if book.rate == 3 %} checked {% endif %} >
                    <label class="custom-control-label mr-1" for="value3">3</label>
                </div>
                <div class="custom-control custom-radio " style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value4" value="4" {% if book.rate == 3 %} checked {% endif %} >
                    <label class="custom-control-label mr-1" for="value4">4</label>
                </div>
                <div class="custom-control custom-radio " style="display: inline;">
                    <input type="radio" class="custom-control-input mr-2" name="rate" id="value5" value="5" {% if book.rate == 5 %} checked {% endif %} >
                    <label class="custom-control-label mr-1" for="value5">5</label>
                </div>
              </div>

            </div>
            <button class="btn btn-outline-info btn-block">Update!</button>
          </div>
        </div>
      </div>
      </form>
    </div>

{%  endblock %}

django-study/simpleProject/templates/book/index.html
{% extends 'base.html' %}
{% load static %}

{% block content  %}
<style>
.card{
border-radius: 15px;
margin-top: 20px;
width: 150px;
height: 220px;
max-width: 175px;
max-height: 220px;
background-size: 100%;
background-repeat: no-repeat;
box-shadow: 0,0,10px;
border: none;
-webkit-column-break-inside: avoid;
cursor: pointer;
}
.list-group{
    display: none;
}
.book-name{
    font-weight: 900;
}
.card:hover{

-webkit-box-shadow: 10px 10px 28px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 10px 10px 28px 0px rgba(0,0,0,0.75);
box-shadow: 10px 10px 28px 0px rgba(0,0,0,0.75);
background-image: none !important;

}
.card:hover ul{
list-style-type: none;
display: block;
}
.btn{
    min-width: 80px;
    
}

@media (min-width: 356px) {
    .card-columns {
        column-count: 3;
        display: "inline";
        display: "inline-block";
    }
}

@media (min-width: 768px) {
    .card-columns {
        column-count: 3;
        display: "inline-block";
    }
}

@media (min-width: 992px) {
    .card-columns {
        column-count: 3;
        display: "inline-block";
        -webkit-column-break-inside: avoid;
    }
}

@media (min-width: 1200px) {
    .card-columns {
        column-count: 5;
        display: "inline-block";
        -webkit-column-break-inside: avoid;
        
    }


}
</style>

<div class="container mt-3">
    <div class="card-columns">
    {% for book in books %}
        <div class="card" style="background-image: url({{book.photo.url}});">
            <ul class="list-group text-center">
                <li>
                    <p class="book-name mt-3">{{book.name}}</p>
                    <p>{{book.author}}</p>
                    <p>{{book.date}}</p>
                    <p>{{book.rate}}/5</p>
                    <form action="{% url 'book:edit' book.id %}">
                        <button class="btn btn-outline-primary waves-effect mt-0">Edit</button>
                    </form>
                </li>
            </ul>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

django-study/simpleProject/templates/messages.html
    <div id="message" class="container ">
        <div class="row justify-content-center" style="position:relative;">
        {% if messages %}
        {% for message in messages %}
            {{message}}
        {% endfor %}
        {% endif %}
        </div>
    </div>

    <script>
        var message = document.getElementById("message")
        setTimeout(function(){
            message.style.display = "none"  
        },5000)
        
    </script>

django-study/simpleProject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Book
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'book:index' %}">List</a>
          <a class="dropdown-item" href="{% url 'book:add' %}">Add</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>